name: Your Github Workflow name
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 10 * * 0'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10.0'      
      - name: InstallDependencies
        run: pip install requests
      - name: CheckOutSome
        env:
            username: ${{ secrets.USERNAME }}
            passward: ${{ secrets.PASSWORD }}
        run: python src/main.py
      
