name: WorkHourBOT
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    # - cron:  '0 10 * * 0'
    - cron: '10 21 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: InstallDependencies
        run: pip install requests
      - name: CheckOutSome
        env:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            sendkey: ${{ secrets.SENDKEY }}
        run: python src/main.py
      
